import { describe, expect, test } from "vite-plus/test";
import { generatedFiles } from "../src/generate.ts";
import { EMPTY_LOCK } from "../src/lock.ts";

describe("catalog generated wiring", () => {
  test("emits all three provenance-marked files for an empty lock", () => {
    const files = generatedFiles(EMPTY_LOCK());
    expect(Object.keys(files).sort()).toEqual([
      "src/catalog/composition.generated.ts",
      "src/catalog/registrations.generated.ts",
      "src/catalog/text.generated.d.ts",
    ]);
    for (const source of Object.values(files))
      expect(source).toContain("Generated by @mit-sdg/sync-engine-catalog. Do not edit.");
  });
});
