import type { CatalogLock, ConceptIntegration, RecipeIntegration } from "./types.ts";

const HEADER = "// Generated by @mit-sdg/sync-engine-catalog. Do not edit.\n";

function importSpecifier(target: string): string {
  return JSON.stringify(`../${target.replace(/^src\//, "")}`);
}

export function generatedFiles(lock: CatalogLock): Record<string, string> {
  const concepts = Object.values(lock.entries)
    .filter((entry) => entry.kind === "concept")
    .map((entry) => entry.integration as ConceptIntegration)
    .sort((left, right) => left.name.localeCompare(right.name));
  const recipes = Object.values(lock.entries)
    .filter((entry) => entry.kind === "recipe")
    .map((entry) => entry.integration as RecipeIntegration)
    .sort((left, right) => left.module.localeCompare(right.module));
  const registrations = concepts
    .map(
      (integration, index) =>
        `import { ${integration.export} as registration${index} } from ${importSpecifier(integration.registration)};`,
    )
    .join("\n");
  const registrationMembers = concepts
    .map((integration, index) => `  ${JSON.stringify(integration.name)}: registration${index},`)
    .join("\n");
  const imports: string[] = [];
  const members: { name: string; local: string }[] = [];
  for (const [recipeIndex, integration] of recipes.entries()) {
    const imported = [...integration.members].sort().map((name, memberIndex) => ({
      name,
      local: `recipe${recipeIndex}Member${memberIndex}`,
    }));
    imports.push(
      `import { ${imported.map(({ name, local }) => `${name} as ${local}`).join(", ")} } from ${importSpecifier(integration.module)};`,
    );
    members.push(...imported);
  }
  return {
    "src/catalog/registrations.generated.ts": `${HEADER}${registrations}${registrations ? "\n\n" : ""}export const catalogRegistrations = {\n${registrationMembers}\n};\n`,
    "src/catalog/composition.generated.ts": `${HEADER}${imports.join("\n")}${imports.length ? "\n\n" : ""}export const catalogComposition = {\n${members
      .sort((left, right) => left.name.localeCompare(right.name))
      .map(({ name, local }) => `  ${JSON.stringify(name)}: ${local},`)
      .join("\n")}\n};\n`,
    "src/catalog/text.generated.d.ts": `${HEADER}declare module "*.md" {\n  const text: string;\n  export default text;\n}\n`,
  };
}
