import { createHash } from "node:crypto";
import { lstat, mkdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import { basename, dirname, isAbsolute, join, posix, relative, resolve, sep } from "node:path";
import type {
  AddOptions,
  CatalogConfig,
  CatalogEntry,
  CatalogFile,
  CatalogLock,
  EntryManifest,
  InitPaths,
  LockedEntry,
  LockedIntegration,
} from "./types.ts";
import {
  catalogVersion,
  entryFiles,
  loadCatalog,
  sourceDigest,
  supportedCoreVersion,
} from "./registry.ts";

const CONFIG_NAME = "catalog.json";
const LOCK_NAME = "catalog.lock";
const GENERATED_HEADER = "// Generated by @mit-sdg/catalog. Do not edit.\n";
const PORTABLE_PATH = /^(?!\/)(?!.*(?:^|\/)\.\.(?:\/|$))(?!.*\\).+$/;
const ENTRY_ID = /^(?:bundle|computation|concept|recipe)\/[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/;
const IDENTIFIER = /^[A-Za-z][A-Za-z0-9]*$/;
const SHA256 = /^[0-9a-f]{64}$/;
const WINDOWS_DEVICE_NAME = /^(?:con|prn|aux|nul|com[1-9]|lpt[1-9])$/i;
const PACKAGE_NAME = /^(?:@[a-z0-9][a-z0-9._-]*\/)?[a-z0-9][a-z0-9._-]*$/;

interface RenderedFile {
  source: string;
  target: string;
  content: string;
  hash: string;
}

interface PlannedEntry {
  id: string;
  lock: LockedEntry;
  files: RenderedFile[];
}

interface InstallationPlan {
  entries: PlannedEntry[];
  lock: CatalogLock;
  warnings: string[];
  alreadyInstalled: string[];
}

export interface MutationResult {
  root: string;
  written: string[];
  warnings: string[];
  alreadyInstalled: string[];
  initialized: boolean;
  integrationRequired?: boolean;
  checkCommand?: string;
}

export interface DiffResult {
  root: string;
  output: string;
  changed: number;
}

export const defaultConfig: CatalogConfig = {
  $schema: 1,
  concepts: "src/concepts",
  computations: "src/computations",
  recipes: "src/composition",
  conceptSet: "src/concept-set.ts",
  declarations: "src/catalog/text.generated.d.ts",
  registrations: "src/catalog/registrations.generated.ts",
  composition: "src/catalog/composition.generated.ts",
};

function hash(content: string): string {
  return createHash("sha256").update(content).digest("hex");
}

function portable(path: string): string {
  return path.split(sep).join(posix.sep);
}

function checkedProjectPath(path: string, owner: string): string {
  if (!PORTABLE_PATH.test(path) || path.includes("\0") || path.includes("//") || isAbsolute(path)) {
    throw new Error(`${owner} must be a project-relative portable path`);
  }
  const normalized = posix.normalize(path.replace(/^\.\//, ""));
  if (normalized === "." || normalized.startsWith("../") || normalized.includes("//")) {
    throw new Error(`${owner} must remain inside the project`);
  }
  for (const segment of normalized.split("/")) {
    const hasControl = Array.from(segment).some((character) => character.charCodeAt(0) < 32);
    const stem = segment.split(".", 1)[0];
    if (
      segment === "." ||
      segment === ".." ||
      hasControl ||
      /[<>:"|?*]/.test(segment) ||
      /[. ]$/.test(segment) ||
      WINDOWS_DEVICE_NAME.test(stem)
    ) {
      throw new Error(`${owner} contains a non-portable path segment: ${segment}`);
    }
  }
  return normalized;
}

function parseConfig(value: unknown): CatalogConfig {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new Error(`${CONFIG_NAME} must contain an object`);
  }
  const found = value as Record<string, unknown>;
  const keys = [
    "$schema",
    "composition",
    "computations",
    "conceptSet",
    "concepts",
    "declarations",
    "recipes",
    "registrations",
  ];
  const unknown = Object.keys(found).filter((key) => !keys.includes(key));
  if (unknown.length > 0)
    throw new Error(`${CONFIG_NAME} has unknown fields: ${unknown.join(", ")}`);
  if (found.$schema !== 1) throw new Error(`${CONFIG_NAME}: $schema must be 1`);
  const path = (key: Exclude<keyof CatalogConfig, "$schema">): string => {
    const value = found[key];
    if (typeof value !== "string") throw new Error(`${CONFIG_NAME}.${key} must be a string`);
    return checkedProjectPath(value, `${CONFIG_NAME}.${key}`);
  };
  const config: CatalogConfig = {
    $schema: 1,
    concepts: path("concepts"),
    computations: path("computations"),
    recipes: path("recipes"),
    conceptSet: path("conceptSet"),
    declarations: path("declarations"),
    registrations: path("registrations"),
    composition: path("composition"),
  };
  for (const [name, value] of [
    ["conceptSet", config.conceptSet],
    ["declarations", config.declarations],
    ["registrations", config.registrations],
    ["composition", config.composition],
  ] as const) {
    const extension = name === "declarations" ? ".d.ts" : ".ts";
    if (!value.endsWith(extension)) {
      throw new Error(`${CONFIG_NAME}.${name} must be a ${extension} file`);
    }
    if (value === CONFIG_NAME || value === LOCK_NAME) {
      throw new Error(`${CONFIG_NAME}.${name} collides with catalog metadata`);
    }
  }
  if (
    new Set([config.conceptSet, config.declarations, config.registrations, config.composition])
      .size !== 4
  ) {
    throw new Error(`${CONFIG_NAME} managed and integration files must use distinct paths`);
  }
  return config;
}

function rejectUnknownFields(
  found: Record<string, unknown>,
  allowed: readonly string[],
  owner: string,
): void {
  const unknown = Object.keys(found).filter((key) => !allowed.includes(key));
  if (unknown.length > 0) throw new Error(`${owner} has unknown fields: ${unknown.join(", ")}`);
}

function parseLock(value: unknown): CatalogLock {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new Error(`${LOCK_NAME} must contain an object`);
  }
  const found = value as Record<string, unknown>;
  rejectUnknownFields(found, ["schema", "entries"], LOCK_NAME);
  if (
    found.schema !== 1 ||
    typeof found.entries !== "object" ||
    found.entries === null ||
    Array.isArray(found.entries)
  ) {
    throw new Error(`${LOCK_NAME} is not a supported catalog lock`);
  }
  const entries: Record<string, LockedEntry> = {};
  for (const [id, rawEntry] of Object.entries(found.entries)) {
    if (
      !ENTRY_ID.test(id) ||
      typeof rawEntry !== "object" ||
      rawEntry === null ||
      Array.isArray(rawEntry)
    ) {
      throw new Error(`${LOCK_NAME}: invalid entry ${id}`);
    }
    const entry = rawEntry as Record<string, unknown>;
    rejectUnknownFields(
      entry,
      [
        "kind",
        "catalogVersion",
        "sourceDigest",
        "requires",
        "packages",
        "variant",
        "files",
        "integration",
      ],
      `${LOCK_NAME}.${id}`,
    );
    const kind = id.split("/", 1)[0];
    if (
      entry.kind !== kind ||
      typeof entry.catalogVersion !== "string" ||
      entry.catalogVersion === "" ||
      typeof entry.sourceDigest !== "string" ||
      !SHA256.test(entry.sourceDigest) ||
      !Array.isArray(entry.requires) ||
      entry.requires.some(
        (dependency) => typeof dependency !== "string" || !ENTRY_ID.test(dependency),
      ) ||
      new Set(entry.requires).size !== entry.requires.length ||
      typeof entry.packages !== "object" ||
      entry.packages === null ||
      Array.isArray(entry.packages) ||
      !Array.isArray(entry.files)
    ) {
      throw new Error(`${LOCK_NAME}: malformed entry ${id}`);
    }
    if (
      entry.variant !== undefined &&
      (typeof entry.variant !== "string" || !/^[a-z][a-z0-9-]*$/.test(entry.variant))
    ) {
      throw new Error(`${LOCK_NAME}: invalid variant for ${id}`);
    }
    const lockedPackages: Record<string, string> = {};
    for (const [name, range] of Object.entries(entry.packages)) {
      if (
        !PACKAGE_NAME.test(name) ||
        typeof range !== "string" ||
        range === "" ||
        /[\r\n]/.test(range)
      ) {
        throw new Error(`${LOCK_NAME}: invalid package requirement for ${id}`);
      }
      lockedPackages[name] = range;
    }
    const files = entry.files.map((rawFile, index) => {
      if (typeof rawFile !== "object" || rawFile === null || Array.isArray(rawFile)) {
        throw new Error(`${LOCK_NAME}: invalid file ${index} for ${id}`);
      }
      const file = rawFile as Record<string, unknown>;
      rejectUnknownFields(file, ["source", "target", "hash"], `${LOCK_NAME}.${id}.files[${index}]`);
      if (
        typeof file.source !== "string" ||
        file.source === "" ||
        posix.isAbsolute(file.source) ||
        file.source.includes("\\") ||
        posix.normalize(file.source) === "." ||
        posix.normalize(file.source).startsWith("../") ||
        typeof file.target !== "string" ||
        typeof file.hash !== "string" ||
        !SHA256.test(file.hash)
      ) {
        throw new Error(`${LOCK_NAME}: invalid file ${index} for ${id}`);
      }
      return {
        source: file.source,
        target: checkedProjectPath(file.target, `${LOCK_NAME}.${id}.files[${index}].target`),
        hash: file.hash,
      };
    });
    let integration: LockedIntegration | undefined;
    if (entry.integration !== undefined) {
      if (
        typeof entry.integration !== "object" ||
        entry.integration === null ||
        Array.isArray(entry.integration)
      ) {
        throw new Error(`${LOCK_NAME}: invalid integration for ${id}`);
      }
      const integrated = entry.integration as Record<string, unknown>;
      if (integrated.kind === "concept") {
        rejectUnknownFields(
          integrated,
          ["kind", "name", "export", "registration"],
          `${LOCK_NAME}.${id}.integration`,
        );
        if (
          kind !== "concept" ||
          typeof integrated.name !== "string" ||
          !IDENTIFIER.test(integrated.name) ||
          typeof integrated.export !== "string" ||
          !IDENTIFIER.test(integrated.export) ||
          typeof integrated.registration !== "string"
        ) {
          throw new Error(`${LOCK_NAME}: invalid concept integration for ${id}`);
        }
        integration = {
          kind: "concept",
          name: integrated.name,
          export: integrated.export,
          registration: checkedProjectPath(
            integrated.registration,
            `${LOCK_NAME}.${id}.integration.registration`,
          ),
        };
      } else if (integrated.kind === "computation") {
        rejectUnknownFields(
          integrated,
          ["kind", "module", "exports"],
          `${LOCK_NAME}.${id}.integration`,
        );
        if (
          kind !== "computation" ||
          typeof integrated.module !== "string" ||
          !Array.isArray(integrated.exports) ||
          integrated.exports.some((name) => typeof name !== "string" || !IDENTIFIER.test(name))
        ) {
          throw new Error(`${LOCK_NAME}: invalid computation integration for ${id}`);
        }
        if (
          integrated.exports.length === 0 ||
          new Set(integrated.exports).size !== integrated.exports.length
        ) {
          throw new Error(`${LOCK_NAME}: repeated computation integration for ${id}`);
        }
        integration = {
          kind: "computation",
          module: checkedProjectPath(integrated.module, `${LOCK_NAME}.${id}.integration.module`),
          exports: [...integrated.exports] as string[],
        };
      } else if (integrated.kind === "recipe") {
        rejectUnknownFields(
          integrated,
          ["kind", "module", "test", "members"],
          `${LOCK_NAME}.${id}.integration`,
        );
        if (
          kind !== "recipe" ||
          typeof integrated.module !== "string" ||
          (integrated.test !== undefined && typeof integrated.test !== "string") ||
          !Array.isArray(integrated.members) ||
          integrated.members.some((name) => typeof name !== "string" || !IDENTIFIER.test(name))
        ) {
          throw new Error(`${LOCK_NAME}: invalid recipe integration for ${id}`);
        }
        if (
          integrated.members.length === 0 ||
          new Set(integrated.members).size !== integrated.members.length
        ) {
          throw new Error(`${LOCK_NAME}: repeated recipe integration for ${id}`);
        }
        integration = {
          kind: "recipe",
          module: checkedProjectPath(integrated.module, `${LOCK_NAME}.${id}.integration.module`),
          ...(integrated.test === undefined
            ? {}
            : {
                test: checkedProjectPath(integrated.test, `${LOCK_NAME}.${id}.integration.test`),
              }),
          members: [...integrated.members] as string[],
        };
      } else {
        throw new Error(`${LOCK_NAME}: unknown integration for ${id}`);
      }
    }
    entries[id] = {
      kind: kind as LockedEntry["kind"],
      catalogVersion: entry.catalogVersion,
      sourceDigest: entry.sourceDigest,
      requires: [...entry.requires] as string[],
      packages: lockedPackages,
      ...(entry.variant === undefined ? {} : { variant: entry.variant as string }),
      files,
      ...(integration === undefined ? {} : { integration }),
    };
    if (
      (kind === "concept" || kind === "computation" || kind === "recipe") &&
      integration === undefined
    ) {
      throw new Error(`${LOCK_NAME}: ${id} is missing integration metadata`);
    }
    if ((kind === "concept") !== (entry.variant !== undefined)) {
      throw new Error(`${LOCK_NAME}: ${id} has invalid variant metadata`);
    }
    if (new Set(files.map(({ target }) => target)).size !== files.length) {
      throw new Error(`${LOCK_NAME}: ${id} repeats a copied target`);
    }
  }
  for (const [id, entry] of Object.entries(entries)) {
    for (const dependency of entry.requires) {
      if (entries[dependency] === undefined) {
        throw new Error(`${LOCK_NAME}: ${id} requires missing entry ${dependency}`);
      }
    }
  }
  const targets = new Map<string, string>();
  for (const [id, entry] of Object.entries(entries)) {
    for (const file of entry.files) {
      const previous = targets.get(file.target);
      if (previous !== undefined) {
        throw new Error(`${LOCK_NAME}: ${id} and ${previous} both own ${file.target}`);
      }
      targets.set(file.target, id);
    }
  }
  const visited = new Set<string>();
  const visiting = new Set<string>();
  function visit(id: string): void {
    if (visited.has(id)) return;
    if (visiting.has(id)) throw new Error(`${LOCK_NAME}: dependency cycle reaches ${id}`);
    visiting.add(id);
    for (const dependency of entries[id]?.requires ?? []) visit(dependency);
    visiting.delete(id);
    visited.add(id);
  }
  for (const id of Object.keys(entries)) visit(id);
  const lock = { schema: 1 as const, entries };
  validateIntegration(lock);
  return lock;
}

function configSource(config: CatalogConfig): string {
  return `${JSON.stringify(config, null, 2)}\n`;
}

function lockSource(lock: CatalogLock): string {
  const entries = Object.fromEntries(
    Object.entries(lock.entries).sort(([left], [right]) => left.localeCompare(right)),
  );
  return `${JSON.stringify({ schema: 1, entries }, null, 2)}\n`;
}

async function pathExists(path: string): Promise<boolean> {
  try {
    await lstat(path);
    return true;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return false;
    throw error;
  }
}

async function assertNoSymlink(root: string, projectPath: string): Promise<void> {
  const parts = checkedProjectPath(projectPath, projectPath).split("/");
  let current = root;
  for (const part of parts) {
    current = join(current, part);
    try {
      const metadata = await lstat(current);
      if (metadata.isSymbolicLink()) {
        throw new Error(
          `${projectPath} passes through symbolic link ${portable(relative(root, current))}`,
        );
      }
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "ENOENT") return;
      throw error;
    }
  }
}

function projectTarget(root: string, projectPath: string): string {
  const checked = checkedProjectPath(projectPath, projectPath);
  const target = resolve(root, checked);
  if (target !== root && !target.startsWith(`${root}${sep}`)) {
    throw new Error(`${projectPath} resolves outside the project`);
  }
  return target;
}

async function projectRoot(start: string): Promise<string> {
  let current = resolve(start);
  for (;;) {
    if (await pathExists(join(current, CONFIG_NAME))) return current;
    const parent = dirname(current);
    if (parent === current) throw new Error(`No ${CONFIG_NAME} found from ${start}`);
    current = parent;
  }
}

async function readProject(start: string): Promise<{
  root: string;
  config: CatalogConfig;
  lock: CatalogLock;
}> {
  const root = await projectRoot(start);
  const config = parseConfig(JSON.parse(await readFile(join(root, CONFIG_NAME), "utf8")));
  const lock = parseLock(JSON.parse(await readFile(join(root, LOCK_NAME), "utf8")));
  return { root, config, lock };
}

function configFor(paths: InitPaths): CatalogConfig {
  return parseConfig({
    ...defaultConfig,
    ...(paths.concepts === undefined ? {} : { concepts: paths.concepts }),
    ...(paths.computations === undefined ? {} : { computations: paths.computations }),
    ...(paths.recipes === undefined ? {} : { recipes: paths.recipes }),
    ...(paths.conceptSet === undefined ? {} : { conceptSet: paths.conceptSet }),
    ...(paths.declarations === undefined ? {} : { declarations: paths.declarations }),
    ...(paths.registrations === undefined ? {} : { registrations: paths.registrations }),
    ...(paths.composition === undefined ? {} : { composition: paths.composition }),
  });
}

function relativeImport(fromProjectPath: string, toProjectPath: string): string {
  let specifier = posix.relative(posix.dirname(fromProjectPath), toProjectPath);
  if (!specifier.startsWith(".")) specifier = `./${specifier}`;
  return specifier;
}

function targetPath(target: string, config: CatalogConfig): string {
  if (target === "$concept-set") return config.conceptSet;
  const roots: Array<[string, string]> = [
    ["$concepts/", config.concepts],
    ["$computations/", config.computations],
    ["$recipes/", config.recipes],
    ["$root/", ""],
  ];
  for (const [token, directory] of roots) {
    if (target.startsWith(token)) {
      return checkedProjectPath(posix.join(directory, target.slice(token.length)), target);
    }
  }
  throw new Error(`catalog target must begin with a supported path token: ${target}`);
}

function renderSource(
  content: string,
  target: string,
  config: CatalogConfig,
  recipeModule?: string,
): string {
  const replacements: Record<string, string> = {
    "@catalog/concepts": relativeImport(target, config.conceptSet),
    "@catalog/registrations": relativeImport(target, config.registrations),
    "@catalog/composition": relativeImport(target, config.composition),
    ...(recipeModule === undefined
      ? {}
      : { "@catalog/recipe": relativeImport(target, recipeModule) }),
  };
  return Object.entries(replacements).reduce(
    (source, [token, replacement]) => source.replaceAll(token, replacement),
    content,
  );
}

function selectedVariant(
  manifest: EntryManifest,
  lock: CatalogLock,
  options: AddOptions,
): string | undefined {
  if (manifest.kind !== "concept") return undefined;
  const installed = lock.entries[manifest.id]?.variant;
  const requested = options.variants.get(manifest.id);
  if (installed !== undefined) {
    if (requested !== undefined && requested !== installed) {
      throw new Error(`${manifest.id} is already tracked with variant ${installed}`);
    }
    return installed;
  }
  const names = Object.keys(manifest.variants ?? {}).sort();
  if (requested !== undefined) {
    if (!names.includes(requested)) {
      throw new Error(`${manifest.id} has variants ${names.join(", ")}; received ${requested}`);
    }
    return requested;
  }
  if (names.length === 1) return names[0];
  throw new Error(
    `${manifest.id} requires --variant ${manifest.id}=<variant>; choose ${names.join(" or ")}`,
  );
}

function recipeTargets(
  manifest: EntryManifest,
  config: CatalogConfig,
  recipeFile: string | undefined,
): { module?: string; test?: string } {
  if (manifest.recipe === undefined) return {};
  const moduleTarget = targetPath(manifest.recipe.module, config);
  const testTarget =
    manifest.recipe.test === undefined ? undefined : targetPath(manifest.recipe.test, config);
  if (recipeFile === undefined) return { module: moduleTarget, test: testTarget };
  if (
    recipeFile.includes("/") ||
    recipeFile.includes("\\") ||
    !/^[a-z][a-z0-9-]*\.ts$/.test(recipeFile)
  ) {
    throw new Error("--file must be a lowercase kebab-case .ts basename");
  }
  const module = posix.join(posix.dirname(moduleTarget), recipeFile);
  const test =
    testTarget === undefined
      ? undefined
      : posix.join(posix.dirname(testTarget), `${recipeFile.slice(0, -3)}.test.ts`);
  return { module, test };
}

function targetForFile(
  file: CatalogFile,
  manifest: EntryManifest,
  config: CatalogConfig,
  targets: { module?: string; test?: string },
): string {
  if (manifest.recipe?.module === file.target && targets.module !== undefined)
    return targets.module;
  if (manifest.recipe?.test === file.target && targets.test !== undefined) return targets.test;
  return targetPath(file.target, config);
}

async function renderEntry(
  entry: CatalogEntry,
  config: CatalogConfig,
  variant: string | undefined,
  version: string,
  recipeFile: string | undefined,
): Promise<PlannedEntry> {
  const targets = recipeTargets(entry.manifest, config, recipeFile);
  const rendered: RenderedFile[] = [];
  for (const file of entryFiles(entry, variant)) {
    const target = targetForFile(file, entry.manifest, config, targets);
    const raw = await readFile(resolve(entry.directory, file.source), "utf8");
    const content = renderSource(raw, target, config, targets.module);
    rendered.push({ source: file.source, target, content, hash: hash(content) });
  }

  let integration: LockedIntegration | undefined;
  if (entry.manifest.concept !== undefined) {
    integration = {
      kind: "concept",
      ...entry.manifest.concept,
      registration: targetPath(entry.manifest.concept.registration, config),
    };
  } else if (entry.manifest.computation !== undefined) {
    integration = {
      kind: "computation",
      ...entry.manifest.computation,
      module: targetPath(entry.manifest.computation.module, config),
    };
  } else if (entry.manifest.recipe !== undefined && targets.module !== undefined) {
    integration = {
      kind: "recipe",
      module: targets.module,
      ...(targets.test === undefined ? {} : { test: targets.test }),
      members: entry.manifest.recipe.members,
    };
  }

  return {
    id: entry.manifest.id,
    files: rendered,
    lock: {
      kind: entry.manifest.kind,
      catalogVersion: version,
      sourceDigest: await sourceDigest(entry, variant),
      requires: [...(entry.manifest.requires ?? [])].sort(),
      packages: packageRequirements(entry.manifest, variant),
      ...(variant === undefined ? {} : { variant }),
      files: rendered.map(({ source, target, hash }) => ({ source, target, hash })),
      ...(integration === undefined ? {} : { integration }),
    },
  };
}

async function localModifications(root: string, entry: LockedEntry): Promise<string[]> {
  const changed: string[] = [];
  for (const file of entry.files) {
    const path = projectTarget(root, file.target);
    if (!(await pathExists(path))) {
      changed.push(file.target);
      continue;
    }
    const content = await readFile(path, "utf8");
    if (hash(content) !== file.hash) changed.push(file.target);
  }
  return changed;
}

function packageRequirements(
  manifest: EntryManifest,
  variant: string | undefined,
): Record<string, string> {
  return {
    ...manifest.packages,
    ...(variant === undefined ? {} : (manifest.variants?.[variant]?.packages ?? {})),
  };
}

function declaredDependencies(manifest: Record<string, unknown>): Record<string, string> {
  const result: Record<string, string> = {};
  for (const field of ["dependencies", "devDependencies", "peerDependencies"] as const) {
    const value = manifest[field];
    if (typeof value !== "object" || value === null || Array.isArray(value)) continue;
    for (const [name, range] of Object.entries(value)) {
      if (typeof range === "string") result[name] = range;
    }
  }
  return result;
}

function acceptsRequiredRange(declared: string | undefined, required: string): boolean {
  if (declared === undefined || /^(?:file|workspace):/.test(declared)) return false;
  if (declared === required) return true;
  const exact = /^(\d+)\.(\d+)\.(\d+)(-[0-9A-Za-z.-]+)?$/.exec(required);
  if (exact === null) return false;
  const [major, minor] = exact.slice(1, 3);
  return (
    declared === `^${required}` ||
    declared === `~${required}` ||
    declared === `>=${required} <${major}.${Number(minor) + 1}.0`
  );
}

async function installedPackageVersion(root: string, name: string): Promise<string | undefined> {
  const path = join(root, "node_modules", ...name.split("/"), "package.json");
  if (!(await pathExists(path))) return undefined;
  const manifest = JSON.parse(await readFile(path, "utf8")) as { version?: unknown };
  return typeof manifest.version === "string" ? manifest.version : undefined;
}

async function checkPackages(
  root: string,
  entryRequirements: Record<string, string>[],
): Promise<string | undefined> {
  const packagePath = join(root, "package.json");
  if (!(await pathExists(packagePath)))
    throw new Error("catalog requires a package.json in the project root");
  const manifest = JSON.parse(await readFile(packagePath, "utf8")) as Record<string, unknown>;
  const declared = declaredDependencies(manifest);
  const requirements: Record<string, string> = {
    "@mit-sdg/sync-engine": await supportedCoreVersion(),
  };
  for (const entry of entryRequirements) {
    for (const [name, range] of Object.entries(entry)) {
      const previous = requirements[name];
      if (previous !== undefined && previous !== range) {
        throw new Error(
          `catalog entries require incompatible ranges for ${name}: ${previous} and ${range}`,
        );
      }
      requirements[name] = range;
    }
  }
  const missing: Array<[string, string]> = [];
  for (const [name, range] of Object.entries(requirements)) {
    const selected = declared[name];
    if (acceptsRequiredRange(selected, range)) continue;
    if (/^(?:file|workspace):/.test(selected ?? "")) {
      const installed = await installedPackageVersion(root, name);
      if (installed !== undefined && acceptsRequiredRange(installed, range)) continue;
    }
    missing.push([name, range]);
  }
  if (missing.length === 0) return undefined;
  const command = `bun add --exact ${missing.map(([name, range]) => `${name}@${range}`).join(" ")}`;
  throw new Error(`Project package requirements are missing or incompatible. Run:\n  ${command}`);
}

async function installationPlan(
  root: string,
  config: CatalogConfig,
  original: CatalogLock,
  requested: string[],
  options: AddOptions,
): Promise<InstallationPlan> {
  if (requested.length === 0) {
    if (options.recipeFile !== undefined) {
      throw new Error("--file requires exactly one explicit recipe entry");
    }
    const unusedVariant = options.variants.keys().next().value;
    if (unusedVariant !== undefined) {
      throw new Error(`--variant selection for ${unusedVariant} is not used by this install`);
    }
    await checkPackages(root, []);
    return { entries: [], lock: original, warnings: [], alreadyInstalled: [] };
  }
  const catalog = await loadCatalog();
  const version = await catalogVersion();
  const requestedSet = new Set(requested);
  if (requestedSet.size !== requested.length)
    throw new Error("catalog entry operands must be unique");
  for (const id of requested) if (!catalog.has(id)) throw new Error(`Unknown catalog entry: ${id}`);

  if (options.recipeFile !== undefined) {
    if (requested.length !== 1 || catalog.get(requested[0])?.manifest.kind !== "recipe") {
      throw new Error("--file requires exactly one explicit recipe entry");
    }
    if (original.entries[requested[0]] !== undefined) {
      throw new Error("--file cannot rename an already tracked recipe");
    }
  }
  for (const id of options.variants.keys()) {
    if (catalog.get(id)?.manifest.kind !== "concept") {
      throw new Error(`--variant names unknown or non-concept entry ${id}`);
    }
  }

  const ordered: Array<{ entry: CatalogEntry; variant?: string }> = [];
  const visiting = new Set<string>();
  const visited = new Set<string>();
  const alreadyInstalled: string[] = [];
  const warnings: string[] = [];
  const encountered = new Set<string>();

  async function visit(id: string, requiredBy?: string): Promise<void> {
    encountered.add(id);
    const entry = catalog.get(id);
    if (entry === undefined)
      throw new Error(`${requiredBy ?? "catalog"} requires unavailable entry ${id}`);
    const installed = original.entries[id];
    if (installed !== undefined) {
      const requestedVariant = options.variants.get(id);
      if (requestedVariant !== undefined && requestedVariant !== installed.variant) {
        throw new Error(`${id} is already tracked with variant ${String(installed.variant)}`);
      }
      if (requiredBy === undefined) alreadyInstalled.push(id);
      else {
        const currentDigest = await sourceDigest(entry, installed.variant);
        if (currentDigest !== installed.sourceDigest) {
          throw new Error(
            `${requiredBy} expects ${id} from this catalog snapshot, but the tracked catalog source differs`,
          );
        }
        const modified = await localModifications(root, installed);
        if (modified.length > 0) {
          warnings.push(
            `${id} has application-owned changes (${modified.join(", ")}); catalog compatibility is not guaranteed`,
          );
        }
      }
      return;
    }
    if (visited.has(id)) return;
    if (visiting.has(id)) throw new Error(`catalog dependency cycle reaches ${id}`);
    visiting.add(id);
    for (const dependency of entry.manifest.requires ?? []) await visit(dependency, id);
    visiting.delete(id);
    visited.add(id);
    ordered.push({ entry, variant: selectedVariant(entry.manifest, original, options) });
  }

  for (const id of requested) await visit(id);
  for (const id of options.variants.keys()) {
    if (!encountered.has(id))
      throw new Error(`--variant selection for ${id} is not used by this install`);
  }

  const selected = new Map<string, string>();
  for (const [id, locked] of Object.entries(original.entries)) {
    if (locked.variant !== undefined) selected.set(id, locked.variant);
  }
  for (const { entry, variant } of ordered)
    if (variant !== undefined) selected.set(entry.manifest.id, variant);
  for (const { entry } of ordered) {
    for (const [id, allowed] of Object.entries(entry.manifest.variantConstraints ?? {})) {
      const actual = selected.get(id);
      if (actual === undefined || !allowed.includes(actual)) {
        throw new Error(`${entry.manifest.id} requires ${id} variant ${allowed.join(" or ")}`);
      }
    }
  }

  await checkPackages(
    root,
    [...encountered].map((id) => {
      const installed = original.entries[id];
      if (installed !== undefined) return installed.packages;
      const selectedEntry = ordered.find(({ entry }) => entry.manifest.id === id);
      return selectedEntry === undefined
        ? {}
        : packageRequirements(selectedEntry.entry.manifest, selectedEntry.variant);
    }),
  );

  const planned: PlannedEntry[] = [];
  const next: CatalogLock = { schema: 1, entries: { ...original.entries } };
  for (const { entry, variant } of ordered) {
    const recipeFile = requestedSet.has(entry.manifest.id) ? options.recipeFile : undefined;
    const rendered = await renderEntry(entry, config, variant, version, recipeFile);
    planned.push(rendered);
    next.entries[rendered.id] = rendered.lock;
  }
  validateIntegration(next);
  return {
    entries: planned,
    lock: next,
    warnings: [...new Set(warnings)].sort(),
    alreadyInstalled: [...new Set(alreadyInstalled)].sort(),
  };
}

function validateIntegration(lock: CatalogLock): void {
  const concepts = new Map<string, string>();
  const computations = new Map<string, string>();
  const members = new Map<string, string>();
  for (const [id, entry] of Object.entries(lock.entries)) {
    const integration = entry.integration;
    if (integration?.kind === "concept") {
      const previous = concepts.get(integration.name);
      if (previous !== undefined)
        throw new Error(`${id} and ${previous} both register ${integration.name}`);
      concepts.set(integration.name, id);
    } else if (integration?.kind === "computation") {
      for (const name of integration.exports) {
        const previous = computations.get(name);
        if (previous !== undefined) throw new Error(`${id} and ${previous} both define ${name}`);
        computations.set(name, id);
      }
    } else if (integration?.kind === "recipe") {
      for (const name of integration.members) {
        const previous = members.get(name);
        if (previous !== undefined) throw new Error(`${id} and ${previous} both compose ${name}`);
        members.set(name, id);
      }
    }
  }
}

function registrationsSource(config: CatalogConfig, lock: CatalogLock): string {
  const concepts = Object.entries(lock.entries)
    .filter(
      (
        entry,
      ): entry is [
        string,
        LockedEntry & { integration: Extract<LockedIntegration, { kind: "concept" }> },
      ] => entry[1].integration?.kind === "concept",
    )
    .sort(([left], [right]) => left.localeCompare(right));
  const computations = Object.entries(lock.entries)
    .filter(
      (
        entry,
      ): entry is [
        string,
        LockedEntry & { integration: Extract<LockedIntegration, { kind: "computation" }> },
      ] => entry[1].integration?.kind === "computation",
    )
    .sort(([left], [right]) => left.localeCompare(right));
  const imports: string[] = [];
  const conceptProperties: string[] = [];
  const computationProperties: string[] = [];
  concepts.forEach(([, entry], index) => {
    const found = entry.integration;
    const local = `catalogConcept${index}`;
    imports.push(
      `import { ${found.export} as ${local} } from ${JSON.stringify(relativeImport(config.registrations, found.registration))};`,
    );
    conceptProperties.push(`  ${found.name}: ${local},`);
  });
  computations.forEach(([, entry], entryIndex) => {
    const found = entry.integration;
    found.exports.forEach((name, exportIndex) => {
      const local = `catalogComputation${entryIndex}_${exportIndex}`;
      imports.push(
        `import { ${name} as ${local} } from ${JSON.stringify(relativeImport(config.registrations, found.module))};`,
      );
      computationProperties.push(`  ${name}: ${local},`);
    });
  });
  return `${GENERATED_HEADER}${imports.length === 0 ? "" : `${imports.join("\n")}\n\n`}export const catalogRegistrations = {\n${conceptProperties.join("\n")}\n};\n\nexport const catalogComputations = {\n${computationProperties.join("\n")}\n};\n`;
}

function declarationsSource(): string {
  return `${GENERATED_HEADER}declare module "*.md" {\n  const text: string;\n  export default text;\n}\n`;
}

function compositionSource(config: CatalogConfig, lock: CatalogLock): string {
  const recipes = Object.entries(lock.entries)
    .filter(
      (
        entry,
      ): entry is [
        string,
        LockedEntry & { integration: Extract<LockedIntegration, { kind: "recipe" }> },
      ] => entry[1].integration?.kind === "recipe",
    )
    .sort(([left], [right]) => left.localeCompare(right));
  const imports = recipes.map(
    ([, entry], index) =>
      `import * as catalogRecipe${index} from ${JSON.stringify(relativeImport(config.composition, entry.integration.module))};`,
  );
  const spreads = recipes.map((_, index) => `  ...catalogRecipe${index},`);
  return `${GENERATED_HEADER}${imports.length === 0 ? "" : `${imports.join("\n")}\n\n`}export const catalogComposition = {\n${spreads.join("\n")}\n};\n`;
}

async function verifyManaged(
  root: string,
  config: CatalogConfig,
  lock: CatalogLock,
): Promise<void> {
  for (const [path, expected] of [
    [config.declarations, declarationsSource()],
    [config.registrations, registrationsSource(config, lock)],
    [config.composition, compositionSource(config, lock)],
  ] as const) {
    const target = projectTarget(root, path);
    if (!(await pathExists(target))) throw new Error(`managed catalog file is missing: ${path}`);
    if ((await readFile(target, "utf8")) !== expected) {
      throw new Error(`managed catalog file was edited: ${path}`);
    }
  }
}

interface WriteSpec {
  path: string;
  content: string;
  replace: boolean;
}

async function commit(root: string, writes: WriteSpec[]): Promise<string[]> {
  const unique = new Set<string>();
  for (const write of writes) {
    if (unique.has(write.path))
      throw new Error(`write plan contains duplicate target ${write.path}`);
    unique.add(write.path);
    await assertNoSymlink(root, write.path);
    const exists = await pathExists(projectTarget(root, write.path));
    if (exists && !write.replace) throw new Error(`refusing to overwrite ${write.path}`);
    if (!exists && write.replace) throw new Error(`managed file is missing: ${write.path}`);
  }

  const created: string[] = [];
  const originals = new Map<string, string>();
  try {
    for (const write of writes) {
      const target = projectTarget(root, write.path);
      await mkdir(dirname(target), { recursive: true });
      if (write.replace) {
        originals.set(write.path, await readFile(target, "utf8"));
        const temporary = `${target}.catalog-${process.pid}-${created.length}`;
        await writeFile(temporary, write.content, { flag: "wx" });
        try {
          await rename(temporary, target);
        } catch (error) {
          await rm(temporary, { force: true });
          throw error;
        }
      } else {
        await writeFile(target, write.content, { flag: "wx" });
        created.push(write.path);
      }
    }
  } catch (error) {
    for (const path of created.reverse()) await rm(projectTarget(root, path), { force: true });
    for (const [path, content] of originals) await writeFile(projectTarget(root, path), content);
    throw error;
  }
  return writes.map(({ path }) => path);
}

async function checkCommand(root: string): Promise<string | undefined> {
  const manifest = JSON.parse(await readFile(join(root, "package.json"), "utf8")) as {
    scripts?: Record<string, unknown>;
  };
  return typeof manifest.scripts?.check === "string" ? "bun run check" : undefined;
}

function planWrites(
  config: CatalogConfig,
  previous: CatalogLock | undefined,
  plan: InstallationPlan,
  initializing: boolean,
): WriteSpec[] {
  const writes: WriteSpec[] = [];
  if (initializing)
    writes.push({ path: CONFIG_NAME, content: configSource(config), replace: false });
  for (const entry of plan.entries) {
    for (const file of entry.files)
      writes.push({ path: file.target, content: file.content, replace: false });
  }
  writes.push({
    path: config.declarations,
    content: declarationsSource(),
    replace: !initializing,
  });
  writes.push({
    path: config.registrations,
    content: registrationsSource(config, plan.lock),
    replace: !initializing,
  });
  writes.push({
    path: config.composition,
    content: compositionSource(config, plan.lock),
    replace: !initializing,
  });
  writes.push({ path: LOCK_NAME, content: lockSource(plan.lock), replace: previous !== undefined });
  return writes;
}

function collisionMessage(
  error: unknown,
  requested: string[],
  plan: InstallationPlan,
  command: "add" | "init",
): Error {
  const prefix = "refusing to overwrite ";
  if (!(error instanceof Error) || !error.message.startsWith(prefix)) {
    return error instanceof Error ? error : new Error(String(error));
  }
  if (requested.length !== 1) return error;
  const entry = plan.entries.find(({ id }) => id === requested[0]);
  const integration = entry?.lock.integration;
  const collision = error.message.slice(prefix.length);
  if (
    integration?.kind !== "recipe" ||
    (collision !== integration.module && collision !== integration.test)
  ) {
    return error;
  }
  const defaultFile = basename(integration.module);
  const alternative = `${basename(defaultFile, ".ts")}-catalog.ts`;
  const retry =
    command === "add"
      ? `Retry with: catalog add ${requested[0]} --file ${alternative}`
      : `Retry the same catalog init command with: --file ${alternative}`;
  return new Error(`${error.message}\n${retry}`);
}

export async function initializeProject(
  start: string,
  paths: InitPaths,
  requested: string[],
  options: AddOptions,
): Promise<MutationResult> {
  const root = resolve(start);
  if (await pathExists(join(root, CONFIG_NAME))) throw new Error(`${CONFIG_NAME} already exists`);
  if (await pathExists(join(root, LOCK_NAME))) throw new Error(`${LOCK_NAME} already exists`);
  const config = configFor(paths);
  const empty: CatalogLock = { schema: 1, entries: {} };
  const plan = await installationPlan(root, config, empty, requested, options);
  const integratesRegistrations = plan.entries.some((entry) =>
    entry.files.some(
      (file) =>
        file.target === config.conceptSet &&
        file.content.includes(relativeImport(config.conceptSet, config.registrations)),
    ),
  );
  const integratesComposition = plan.entries.some((entry) =>
    entry.files.some((file) =>
      file.content.includes(relativeImport(file.target, config.composition)),
    ),
  );
  let written: string[];
  try {
    written = await commit(root, planWrites(config, undefined, plan, true));
  } catch (error) {
    throw collisionMessage(error, requested, plan, "init");
  }
  return {
    root,
    written,
    warnings: plan.warnings,
    alreadyInstalled: plan.alreadyInstalled,
    initialized: true,
    integrationRequired: !integratesRegistrations || !integratesComposition,
    checkCommand: await checkCommand(root),
  };
}

export async function addEntries(
  start: string,
  requested: string[],
  options: AddOptions,
): Promise<MutationResult> {
  if (requested.length === 0) throw new Error("catalog add requires at least one entry");
  const { root, config, lock } = await readProject(start);
  await verifyManaged(root, config, lock);
  const plan = await installationPlan(root, config, lock, requested, options);
  if (plan.entries.length === 0) {
    return {
      root,
      written: [],
      warnings: plan.warnings,
      alreadyInstalled: plan.alreadyInstalled,
      initialized: false,
      checkCommand: await checkCommand(root),
    };
  }
  let written: string[];
  try {
    written = await commit(root, planWrites(config, lock, plan, false));
  } catch (error) {
    throw collisionMessage(error, requested, plan, "add");
  }
  return {
    root,
    written,
    warnings: plan.warnings,
    alreadyInstalled: plan.alreadyInstalled,
    initialized: false,
    checkCommand: await checkCommand(root),
  };
}

function unifiedDifference(path: string, local: string, catalog: string): string {
  const left = local.replace(/\n$/, "").split("\n");
  const right = catalog.replace(/\n$/, "").split("\n");
  let prefix = 0;
  while (prefix < left.length && prefix < right.length && left[prefix] === right[prefix]) prefix++;
  let suffix = 0;
  while (
    suffix < left.length - prefix &&
    suffix < right.length - prefix &&
    left[left.length - 1 - suffix] === right[right.length - 1 - suffix]
  ) {
    suffix++;
  }
  const contextStart = Math.max(0, prefix - 3);
  const leftEnd = Math.min(left.length, left.length - suffix + 3);
  const rightEnd = Math.min(right.length, right.length - suffix + 3);
  const lines = [
    `--- ${path} (local)`,
    `+++ ${path} (catalog)`,
    `@@ -${contextStart + 1},${leftEnd - contextStart} +${contextStart + 1},${rightEnd - contextStart} @@`,
  ];
  for (let index = contextStart; index < prefix; index++) lines.push(` ${left[index]}`);
  for (let index = prefix; index < left.length - suffix; index++) lines.push(`-${left[index]}`);
  for (let index = prefix; index < right.length - suffix; index++) lines.push(`+${right[index]}`);
  for (let index = Math.max(prefix, right.length - suffix); index < rightEnd; index++) {
    lines.push(` ${right[index]}`);
  }
  return lines.join("\n");
}

export async function diffEntries(start: string, requested: string[]): Promise<DiffResult> {
  const { root, config, lock } = await readProject(start);
  const catalog = await loadCatalog();
  const ids = requested.length === 0 ? Object.keys(lock.entries).sort() : requested;
  if (new Set(ids).size !== ids.length) throw new Error("catalog entry operands must be unique");
  const sections: string[] = [];
  let changed = 0;
  for (const id of ids) {
    const installed = lock.entries[id];
    if (installed === undefined) throw new Error(`${id} is not tracked`);
    const entry = catalog.get(id);
    if (entry === undefined) {
      sections.push(`${id}: absent from this catalog snapshot`);
      changed++;
      continue;
    }
    const recipeFile =
      installed.integration?.kind === "recipe" ? basename(installed.integration.module) : undefined;
    const current = await renderEntry(
      entry,
      config,
      installed.variant,
      await catalogVersion(),
      recipeFile,
    );
    const currentTargets = new Set(current.files.map(({ target }) => target));
    for (const file of installed.files) {
      if (!currentTargets.has(file.target)) {
        sections.push(`${file.target}: tracked locally but absent from this catalog snapshot`);
        changed++;
      }
    }
    for (const file of current.files) {
      const localPath = projectTarget(root, file.target);
      if (!(await pathExists(localPath))) {
        sections.push(
          `--- ${file.target} (missing)\n+++ ${file.target} (catalog)\n${file.content}`,
        );
        changed++;
        continue;
      }
      const local = await readFile(localPath, "utf8");
      if (local !== file.content) {
        sections.push(unifiedDifference(file.target, local, file.content));
        changed++;
      }
    }
  }
  return {
    root,
    output: sections.length === 0 ? "No catalog differences." : sections.join("\n\n"),
    changed,
  };
}

export async function forgetEntries(start: string, requested: string[]): Promise<MutationResult> {
  if (requested.length === 0) throw new Error("catalog forget requires at least one entry");
  const { root, config, lock } = await readProject(start);
  await verifyManaged(root, config, lock);
  const targets = new Set(requested);
  if (targets.size !== requested.length) throw new Error("catalog entry operands must be unique");
  for (const id of targets)
    if (lock.entries[id] === undefined) throw new Error(`${id} is not tracked`);
  for (const [id, entry] of Object.entries(lock.entries)) {
    if (targets.has(id)) continue;
    const dependency = entry.requires.find((required) => targets.has(required));
    if (dependency !== undefined) throw new Error(`${id} still depends on ${dependency}`);
  }
  const entries = Object.fromEntries(
    Object.entries(lock.entries).filter(([id]) => !targets.has(id)),
  );
  const next: CatalogLock = { schema: 1, entries };
  validateIntegration(next);
  const writes: WriteSpec[] = [
    {
      path: config.registrations,
      content: registrationsSource(config, next),
      replace: true,
    },
    { path: config.composition, content: compositionSource(config, next), replace: true },
    { path: LOCK_NAME, content: lockSource(next), replace: true },
  ];
  const written = await commit(root, writes);
  return {
    root,
    written,
    warnings: ["Copied source was not deleted; it is application-owned."],
    alreadyInstalled: [],
    initialized: false,
    checkCommand: await checkCommand(root),
  };
}

export function integrationInstructions(config: CatalogConfig = defaultConfig): string[] {
  return [
    `Import catalogRegistrations and catalogComputations from ${config.registrations}, then pass them to conceptSet(...).`,
    `Import catalogComposition from ${config.composition}, then spread it into assembled composition.`,
  ];
}

export async function readConfigFrom(root: string): Promise<CatalogConfig> {
  return parseConfig(JSON.parse(await readFile(join(root, CONFIG_NAME), "utf8")));
}
