import { renderInputContracts } from "@engine/boundary/protocol/endpoints";
import type { WireContractsIR } from "@engine/boundary/wire/wire-contracts";
import { renderWireTypes } from "@engine/boundary/wire/wire-renderer";
import { assertApplicationLocality } from "@engine/boundary/assembly/locality-validation";
import { renderApp } from "@engine/reads/render";
import { canonicalDigest } from "@engine/utils/canonical-json";
import { ordinal } from "@engine/utils/ordinal";
import {
  assertCurrentGenerator,
  PACKAGE_NAME,
  PACKAGE_VERSION,
} from "@engine/utils/package-version";
import type { ApplicationManifestV3 } from "./manifest.ts";

export type ArtifactKind = "specification" | "wire" | "manifest";

export interface ArtifactPlanEntry {
  path: string;
  content: string;
  kind: ArtifactKind;
  digest: string;
}

export interface ArtifactPlan {
  entries: ArtifactPlanEntry[];
}

export interface GeneratedPlanOptions {
  title: string;
  specification?: string;
  specificationBanner?: string;
  wire?: string;
  wireName?: string;
  wireBanner?: string;
  vocabulary?: { from: string; export: string };
  strictLeaves?: boolean;
  /** An HTTP contract already projected by the owning boundary policy. */
  httpWire?: WireContractsIR;
  httpWireName?: string;
}

export type ArtifactStatus =
  | { path: string; kind: ArtifactKind; status: "missing" | "changed" | "unchanged" }
  | { path: string; kind: ArtifactKind; status: "failed"; errorClass: string };

export interface ArtifactFilesystem {
  read(path: string): Promise<string | undefined>;
  /** The adapter must write a same-directory temporary file and rename it. */
  writeAtomic(path: string, content: string): Promise<void>;
}

function errorClass(error: unknown): string {
  return error instanceof Error && error.constructor.name !== "" ? error.constructor.name : "Error";
}

export function normalizeArtifactPath(path: string): string {
  if (
    typeof path !== "string" ||
    path === "" ||
    path.startsWith("/") ||
    path.includes("\\") ||
    path.includes("%") ||
    path.includes("?") ||
    path.includes("#") ||
    path.includes(":")
  ) {
    throw new Error(
      `Artifact path "${path}" must be a non-empty relative POSIX path without URL metacharacters.`,
    );
  }
  const parts = path.split("/");
  const unsafe = parts.some((part) => part === "" || part === "." || part === "..");
  if (unsafe) {
    throw new Error(`Artifact path "${path}" escapes or does not normalize within its directory.`);
  }
  return parts.join("/");
}

export function artifactPlan(entries: readonly Omit<ArtifactPlanEntry, "digest">[]): ArtifactPlan {
  const paths = new Set<string>();
  const planned = entries.map((entry) => {
    const path = normalizeArtifactPath(entry.path);
    if (paths.has(path)) throw new Error(`Artifact plan contains duplicate path "${path}".`);
    paths.add(path);
    if (typeof entry.content !== "string") {
      throw new Error(`Artifact "${path}" content must be a string.`);
    }
    return { ...entry, path, digest: canonicalDigest(entry.content) };
  });
  return { entries: planned.sort((left, right) => ordinal(left.path, right.path)) };
}

export function planGenerated(
  manifest: ApplicationManifestV3,
  options: GeneratedPlanOptions,
): ArtifactPlan {
  if (manifest.format !== "sync-engine.application-manifest" || manifest.version !== 3) {
    throw new Error("generated artifacts: requires an application manifest at version 3.");
  }
  assertCurrentGenerator(manifest.generator, "generated artifacts");
  assertApplicationLocality("generated artifacts", manifest.application);
  const specification = options.specification ?? "application.md";
  const wire = options.wire ?? "wire.ts";
  const wireName = options.wireName ?? "ApplicationWire";
  const generator = `${PACKAGE_NAME}@${PACKAGE_VERSION}`;
  const specificationBanner =
    options.specificationBanner === undefined
      ? `<!-- Generated by ${generator} from the ${options.title} assembly. Do not edit. -->`
      : `${options.specificationBanner}\n<!-- Generator: ${generator}. -->`;
  const wireBanner =
    options.wireBanner === undefined
      ? `// Generated by ${generator} from the ${options.title} assembly. Do not edit.`
      : `${options.wireBanner}\n// Generator: ${generator}.`;
  const logicalWire = renderWireTypes(manifest.wire, {
    moduleName: wireName,
    ...(options.vocabulary === undefined ? {} : { vocabulary: options.vocabulary }),
    strictLeaves: options.strictLeaves ?? false,
  });
  const renderedWire = (
    options.httpWire === undefined
      ? logicalWire
      : logicalWire +
        "\n" +
        renderWireTypes(options.httpWire, {
          moduleName: options.httpWireName ?? `${wireName}Http`,
          appWideErrorName: "HttpAppWideError",
          ...(options.vocabulary === undefined ? {} : { vocabulary: options.vocabulary }),
          strictLeaves: options.strictLeaves ?? false,
          preamble: false,
        })
  ).replace(/^\/\/ Generated wire contracts.*\n\/\/ Regenerated.*\n/, `${wireBanner}\n`);
  return artifactPlan([
    {
      path: specification,
      kind: "specification",
      content:
        `${specificationBanner}\n\n` +
        renderApp({
          title: options.title,
          concepts: manifest.concepts,
          app: manifest.application,
        }) +
        "\n" +
        renderInputContracts(manifest.inputContracts),
    },
    { path: wire, kind: "wire", content: renderedWire },
  ]);
}

export async function checkArtifactPlan(
  plan: ArtifactPlan,
  filesystem: ArtifactFilesystem,
): Promise<ArtifactStatus[]> {
  return Promise.all(
    plan.entries.map(async ({ path, content, kind }) => {
      try {
        const current = await filesystem.read(path);
        return {
          path,
          kind,
          status: current === undefined ? "missing" : current === content ? "unchanged" : "changed",
        } as ArtifactStatus;
      } catch (error) {
        return { path, kind, status: "failed", errorClass: errorClass(error) };
      }
    }),
  );
}

export async function applyArtifactPlan(
  plan: ArtifactPlan,
  filesystem: ArtifactFilesystem,
): Promise<ArtifactStatus[]> {
  // Revalidate every entry before the first effect, including plans assembled by hand.
  const validated = artifactPlan(
    plan.entries.map(({ path, content, kind }) => ({ path, content, kind })),
  );
  const status = await checkArtifactPlan(validated, filesystem);
  if (status.some(({ status: state }) => state === "failed")) return status;
  const byPath = new Map(validated.entries.map((entry) => [entry.path, entry]));
  for (let index = 0; index < status.length; index++) {
    const entryStatus = status[index];
    if (entryStatus === undefined || entryStatus.status === "unchanged") continue;
    const entry = byPath.get(entryStatus.path);
    if (entry === undefined) continue;
    try {
      await filesystem.writeAtomic(entry.path, entry.content);
    } catch (error) {
      status[index] = {
        path: entry.path,
        kind: entry.kind,
        status: "failed",
        errorClass: errorClass(error),
      };
    }
  }
  return status;
}
