import { existsSync } from "node:fs";
import { mkdir, readFile, rename, unlink, writeFile } from "node:fs/promises";
import { dirname, posix, relative } from "node:path";
import { fileURLToPath } from "node:url";
import type { Assembly } from "@engine/boundary/assembly/assembly-facade";
import { assemblyBehind } from "@engine/boundary/assembly/assembly-registry";
import { assertPortableEndpoints } from "@engine/boundary/assembly/endpoint-portability";
import type { HttpFloor } from "@engine/boundary/http/http-floor";
import { projectAssemblyHttpWire } from "@engine/boundary/http/http-floor";
import { renderInputContracts } from "@engine/boundary/protocol/endpoints";
import { wireContracts } from "@engine/boundary/wire/wire-contracts";
import { renderWireTypes } from "@engine/boundary/wire/wire-renderer";
import { renderApp } from "@engine/reads/render";
import { pascal, slug } from "@engine/utils/case";
import { inspectAssembly } from "./inspection.ts";
import {
  applyArtifactPlan,
  artifactPlan,
  checkArtifactPlan,
  type ArtifactFilesystem,
  type ArtifactPlan,
} from "./artifact-plan.ts";

type InspectableAssembly = Assembly<Record<string, new (...args: never[]) => object>>;

/**
 * What a project's `generated.config.ts` declares. Only `assemble` and `title`
 * are required — every path and name below follows from the title and the
 * config's own location, and each may be overridden.
 */
export interface GeneratedApplication {
  assemble: () => InspectableAssembly;
  /** The application's name, used as the document title and to derive the rest. */
  title: string;
  /** Where generated files are written; defaults to `generated/` beside the config. */
  directory?: URL;
  /** The read-back's filename; defaults to the title, slugged, with `.md`. */
  specification?: string;
  /** The wire contract's filename; defaults to `wire.ts`. */
  wire?: string;
  /** The wire contract's type name; defaults to the title in Pascal case, with `Wire`. */
  wireName?: string;
  /** The wire contract's banner; defaults to one naming the assembly. */
  wireBanner?: string;
  /** HTTP-projected contract name; defaults to `${wireName}Http`. */
  httpWireName?: string;
  /**
   * The module whose export anchors generated wire types to concept
   * signatures; defaults to `src/concept-set.ts` beside the config, exporting
   * `vocabulary`.
   */
  vocabulary?: { module?: URL; export?: string };
  httpFloor?: HttpFloor;
}

type ResolvedApplication = GeneratedApplication & {
  directory: URL;
  specification: string;
  wire: string;
  wireName: string;
  wireBanner: string;
  /** The specifier the generated wire imports its type anchor from. */
  vocabularyFrom: { from: string; export: string };
};

/** The module specifier a file in `directory` uses to reach `target`. */
function specifierFrom(directory: URL, target: URL): string {
  const path = relative(fileURLToPath(directory), fileURLToPath(target)).split(/[\\/]/).join("/");
  return path.startsWith(".") ? path : `./${path}`;
}

/**
 * Fill an application's defaults from its title and the location of the config
 * that declared it.
 */
export function resolveApplication(
  application: GeneratedApplication,
  config: URL,
): ResolvedApplication {
  if (typeof application.title !== "string" || application.title.trim() === "") {
    throw new Error("generated config: title must name the application.");
  }
  if (typeof application.assemble !== "function") {
    throw new Error("generated config: assemble must build the application.");
  }
  const directory = application.directory ?? new URL("./generated/", config);
  const module = application.vocabulary?.module ?? new URL("./src/concept-set.ts", config);
  if (!existsSync(module)) {
    throw new Error(
      `generated config: no vocabulary module at ${fileURLToPath(module)} — ` +
        "point `vocabulary.module` at the file exporting the concept set.",
    );
  }
  return {
    ...application,
    directory,
    specification: application.specification ?? `${slug(application.title)}.md`,
    wire: application.wire ?? "wire.ts",
    wireName: application.wireName ?? `${pascal(application.title)}Wire`,
    wireBanner:
      application.wireBanner ??
      `// Generated by sync-engine from the ${application.title} assembly. Do not edit.`,
    vocabularyFrom: {
      from: posix.normalize(specifierFrom(directory, module)),
      export: application.vocabulary?.export ?? "vocabulary",
    },
  };
}

export function renderGenerated(application: ResolvedApplication) {
  const assembled = application.assemble();
  const design = inspectAssembly(assembled);
  const endpointOfReaction = assemblyBehind(assembled).endpointOfReaction;
  assertPortableEndpoints("generated artifacts", design.app.unlowered, endpointOfReaction);
  const applicationContracts = wireContracts(design.app, {
    contracts: design.inputContracts,
    inventories: design.concepts,
  });
  const { wireName } = application;
  const logicalWire = renderWireTypes(applicationContracts, {
    moduleName: wireName,
    vocabulary: application.vocabularyFrom,
    strictLeaves: true,
  });
  const wire =
    application.httpFloor === undefined
      ? logicalWire
      : logicalWire +
        "\n" +
        renderWireTypes(
          projectAssemblyHttpWire(assembled, applicationContracts, application.httpFloor),
          {
            moduleName: application.httpWireName ?? `${wireName}Http`,
            appWideErrorName: "HttpAppWideError",
            vocabulary: application.vocabularyFrom,
            strictLeaves: true,
            preamble: false,
          },
        );
  return {
    metrics: {
      reactions: design.app.reactions.length,
      views: design.app.views?.length ?? 0,
      formers: design.app.formers?.length ?? 0,
      unlowered: design.app.unlowered ?? [],
      compute: JSON.stringify(design.app).match(/"op":"compute"/g)?.length ?? 0,
    },
    specification:
      `<!-- Generated by sync-engine from the ${application.title} assembly. Do not edit. -->\n\n` +
      renderApp({ title: application.title, concepts: design.concepts, app: design.app }) +
      "\n" +
      renderInputContracts(design.inputContracts),
    wire: wire.replace(
      /^\/\/ Generated wire contracts.*\n\/\/ Regenerated.*\n/,
      `${application.wireBanner}\n`,
    ),
  };
}

function generatedPlan(
  application: ResolvedApplication,
  artifact: "all" | "specification" | "wire" = "all",
): ArtifactPlan {
  const rendered = renderGenerated(application);
  return artifactPlan([
    ...(artifact === "wire"
      ? []
      : [
          {
            path: application.specification,
            content: rendered.specification,
            kind: "specification" as const,
          },
        ]),
    ...(artifact === "specification"
      ? []
      : [{ path: application.wire, content: rendered.wire, kind: "wire" as const }]),
  ]);
}

function nodeFilesystem(directory: URL): ArtifactFilesystem {
  return {
    async read(path) {
      try {
        return await readFile(new URL(path, directory), "utf8");
      } catch (error) {
        if ((error as { code?: unknown }).code === "ENOENT") return undefined;
        throw error;
      }
    },
    async writeAtomic(path, content) {
      const target = fileURLToPath(new URL(path, directory));
      await mkdir(dirname(target), { recursive: true });
      const temporary = `${target}.${crypto.randomUUID()}.tmp`;
      try {
        await writeFile(temporary, content);
        await rename(temporary, target);
      } catch (error) {
        await unlink(temporary).catch(() => undefined);
        throw error;
      }
    },
  };
}

export async function pinGenerated(
  application: ResolvedApplication,
  artifact: "all" | "specification" | "wire" = "all",
): Promise<void> {
  const status = await applyArtifactPlan(
    generatedPlan(application, artifact),
    nodeFilesystem(application.directory),
  );
  const failed = status.filter(({ status: state }) => state === "failed");
  if (failed.length > 0) {
    throw new Error(
      `generated artifacts: failed to apply ${failed.map(({ path }) => path).join(", ")}`,
    );
  }
}

export async function checkGenerated(application: ResolvedApplication): Promise<void> {
  const status = await checkArtifactPlan(
    generatedPlan(application),
    nodeFilesystem(application.directory),
  );
  const failed = status.filter(({ status: state }) => state === "failed");
  if (failed.length > 0) {
    throw new Error(
      `generated artifacts: failed to check ${failed.map(({ path }) => path).join(", ")}`,
    );
  }
  const mismatches = status
    .filter(({ status: state }) => state !== "unchanged")
    .map(({ path }) => path);
  if (mismatches.length > 0) {
    throw new Error(
      `${mismatches.join(" and ")} differ from generated output; inspect the changes and run the matching pin command`,
    );
  }
}
