import { mkdir, readFile, writeFile } from "node:fs/promises";
import type { Assembly } from "../boundary/assembly-facade.ts";
import { renderInputContracts } from "../boundary/endpoints.ts";
import { renderWireTypes, wireContracts } from "../boundary/wire.ts";
import type { HttpFloor } from "../boundary/http-floor.ts";
import { projectAssemblyHttpWire } from "../boundary/http-floor.ts";
import { renderApp } from "../reads/render.ts";
import { inspectAssembly } from "./inspection.ts";

type InspectableAssembly = Assembly<Record<string, new (...args: never[]) => object>>;

export interface GeneratedApplication {
  assemble: () => InspectableAssembly;
  directory: URL;
  specification: string;
  title: string;
  wire: string;
  wireBanner?: string;
  wireName?: string;
  /** HTTP-projected contract name; defaults to `${wireName}Http`. */
  httpWireName?: string;
  wireVocabulary: { from: string; export: string };
  httpFloor?: HttpFloor;
}

export function renderGenerated(application: GeneratedApplication) {
  const assembled = application.assemble();
  const design = inspectAssembly(assembled);
  const applicationContracts = wireContracts(design.app, {
    contracts: design.inputContracts,
    inventories: design.concepts,
  });
  const wireName = application.wireName ?? "WireContracts";
  const logicalWire = renderWireTypes(applicationContracts, {
    moduleName: wireName,
    vocabulary: application.wireVocabulary,
    strictLeaves: true,
  });
  const wire =
    application.httpFloor === undefined
      ? logicalWire
      : logicalWire +
        "\n" +
        renderWireTypes(
          projectAssemblyHttpWire(assembled, applicationContracts, application.httpFloor),
          {
            moduleName: application.httpWireName ?? `${wireName}Http`,
            appWideErrorName: "HttpAppWideError",
            vocabulary: application.wireVocabulary,
            strictLeaves: true,
            preamble: false,
          },
        );
  return {
    metrics: {
      reactions: design.app.reactions.length,
      views: design.app.views?.length ?? 0,
      formers: design.app.formers?.length ?? 0,
      unlowered: design.app.unlowered ?? [],
      compute: JSON.stringify(design.app).match(/"op":"compute"/g)?.length ?? 0,
    },
    specification:
      `<!-- Generated by sync-engine from the ${application.title} assembly. Do not edit. -->\n\n` +
      renderApp({ title: application.title, concepts: design.concepts, app: design.app }) +
      "\n" +
      renderInputContracts(design.inputContracts),
    wire:
      application.wireBanner === undefined
        ? wire
        : wire.replace(
            /^\/\/ Generated wire contracts.*\n\/\/ Regenerated.*\n/,
            `${application.wireBanner}\n`,
          ),
  };
}

export async function pinGenerated(
  application: GeneratedApplication,
  artifact: "all" | "specification" | "wire" = "all",
): Promise<void> {
  const rendered = renderGenerated(application);
  await mkdir(application.directory, { recursive: true });
  const writes: Promise<void>[] = [];
  if (artifact !== "wire") {
    writes.push(
      writeFile(new URL(application.specification, application.directory), rendered.specification),
    );
  }
  if (artifact !== "specification") {
    writes.push(writeFile(new URL(application.wire, application.directory), rendered.wire));
  }
  await Promise.all(writes);
}

export async function checkGenerated(application: GeneratedApplication): Promise<void> {
  const rendered = renderGenerated(application);
  const [specification, wire] = await Promise.all([
    readFile(new URL(application.specification, application.directory), "utf8"),
    readFile(new URL(application.wire, application.directory), "utf8"),
  ]);
  const mismatches = [
    ...(rendered.specification === specification ? [] : [application.specification]),
    ...(rendered.wire === wire ? [] : [application.wire]),
  ];
  if (mismatches.length > 0) {
    throw new Error(
      `${mismatches.join(" and ")} differ from generated output; inspect the changes and run the matching pin command`,
    );
  }
}
