import { assembleOperationsRoom } from "./src/assembly.ts";

export default {
  assemble: assembleOperationsRoom,
  directory: new URL("./generated/", import.meta.url),
  specification: "operations-room.md",
  title: "Operations room",
  wire: "wire.ts",
  wireBanner: "// Generated by sync-engine from the Operations room assembly. Do not edit.",
  wireName: "OperationsRoomWire",
  wireVocabulary: { from: "../src/concept-set.ts", export: "vocabulary" },
};
