import { access, readFile, writeFile } from "node:fs/promises";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { filesBelow } from "../src/command/files-below.ts";
import { workspaceBuildOrder, workspacePath, type Workspace } from "./workspaces.ts";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

interface PackageManifest {
  exports: Record<string, { types?: string }>;
}

async function declarationsFor(workspace: Workspace): Promise<string[]> {
  const dist = workspacePath(root, workspace, workspace.distDirectory);
  const declarations = (await filesBelow(dist, (name) => name.endsWith(".d.ts"))).sort();
  if (declarations.length === 0) {
    throw new Error(`${workspace.id} emitted no declaration files`);
  }
  return declarations;
}

async function validateDeclarations(workspace: Workspace): Promise<void> {
  const manifest = JSON.parse(
    await readFile(resolve(root, workspace.packageManifest), "utf8"),
  ) as PackageManifest;
  if (Object.keys(manifest.exports).length === 0) return;
  const declarations = await declarationsFor(workspace);
  for (const path of declarations) {
    const source = await readFile(path, "utf8");
    if (source.includes("@engine/") || source.includes("@root/")) {
      throw new Error(`${relative(root, path)} contains a repository-only declaration alias`);
    }
  }

  for (const [entrypoint, target] of Object.entries(manifest.exports)) {
    if (typeof target.types !== "string") {
      throw new Error(`${workspace.id} export ${entrypoint} does not declare a types target`);
    }
    await access(workspacePath(root, workspace, target.types.replace(/^\.\//, "")));
  }
}

async function renderSnapshot(workspace: Workspace): Promise<string> {
  if (workspace.buildConfig === undefined) {
    throw new Error(`${workspace.id} has a declaration snapshot but no build configuration`);
  }
  const files = await declarationsFor(workspace);
  const sections = await Promise.all(
    files.map(async (path) => {
      const name = relative(root, path);
      const declaration = (await readFile(path, "utf8")).trimEnd();
      return `=== ${name} ===\n${declaration}`;
    }),
  );
  return [
    `# Generated by \`bun run declarations:pin\` from ${workspace.buildConfig}. Do not edit.`,
    "",
    sections.join("\n\n"),
    "",
  ].join("\n");
}

const mode = process.argv[2];
if (mode !== "pin" && mode !== "check") {
  throw new Error("usage: declarations.ts <check|pin>");
}

for (const workspace of workspaceBuildOrder) await validateDeclarations(workspace);

for (const workspace of workspaceBuildOrder) {
  if (workspace.declarationSnapshot === undefined) continue;
  const actual = await renderSnapshot(workspace);
  const snapshotPath = resolve(root, workspace.declarationSnapshot);
  if (mode === "pin") {
    await writeFile(snapshotPath, actual);
  } else {
    const expected = await readFile(snapshotPath, "utf8");
    if (actual !== expected) {
      throw new Error(
        `${workspace.id} emitted declarations differ; inspect the build and run declarations:pin`,
      );
    }
  }
}
