import { readFile, writeFile } from "node:fs/promises";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { filesBelow } from "./walk.ts";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const declarations = resolve(root, "dist");
const snapshotPath = resolve(root, "tests/package/declarations.snapshot.txt");

async function renderSnapshot(): Promise<string> {
  const files = (await filesBelow(declarations, (name) => name.endsWith(".d.ts"))).sort();
  const sections = await Promise.all(
    files.map(async (path) => {
      const name = relative(root, path);
      const declaration = (await readFile(path, "utf8")).trimEnd();
      return `=== ${name} ===\n${declaration}`;
    }),
  );
  return [
    "# Generated by `bun run declarations:pin` from tsconfig.build.json. Do not edit.",
    "",
    sections.join("\n\n"),
    "",
  ].join("\n");
}

const mode = process.argv[2];
const actual = await renderSnapshot();

if (mode === "pin") {
  await writeFile(snapshotPath, actual);
} else if (mode === "check") {
  const expected = await readFile(snapshotPath, "utf8");
  if (actual !== expected) {
    throw new Error("emitted declarations differ; inspect the build and run declarations:pin");
  }
} else {
  throw new Error("usage: declarations.ts <check|pin>");
}
